//go:build windows && cgo

package tray

import (
	_ "embed"

	"github.com/energye/systray"
)

// icon is the .ico generated by scripts/gen-tray-icon.py.
//
//go:embed mobiledeck.ico
var icon []byte

// Start puts the icon in the notification area and blocks until Stop is called.
//
// It blocks on the tray's own event loop, which is why the caller runs it on a
// goroutine: the notification area needs a message loop on a thread locked to
// it, and that is not the thread the web view's loop owns.
func Start(opts Options, cb Callbacks) {
	systray.Run(func() {
		systray.SetIcon(icon)
		systray.SetTooltip(opts.Title)

		// A left click is the fastest way back to the window and the first thing
		// the user will try; the menu is on the right button, where Windows puts
		// it.
		systray.SetOnClick(func(systray.IMenu) { cb.Show() })
		systray.SetOnDClick(func(systray.IMenu) { cb.Show() })

		show := systray.AddMenuItem("Show the control panel", "Open the window")
		show.Click(cb.Show)

		if opts.Address != "" {
			// Disabled rather than absent: it answers "what do I type into the
			// phone", and a menu line that cannot be clicked is how a tray menu
			// shows a label.
			where := systray.AddMenuItem("Reachable at "+opts.Address, "The address the phone connects to")
			where.Disable()
		}

		systray.AddSeparator()
		quit := systray.AddMenuItem("Quit MobileDeck", "Stop the host and close the window")
		quit.Click(cb.Quit)

		close(ready)
	}, func() {})
}

// ready is closed once the icon exists, so a caller that needs the icon to be
// visible before it reports success can wait instead of guessing.
var ready = make(chan struct{})

// Ready returns a channel closed when the icon is in the notification area.
func Ready() <-chan struct{} { return ready }

// Stop removes the icon and ends the loop Start is blocked on.
func Stop() { systray.Quit() }

// Available reports whether this build can show an icon in the notification
// area. It is true here by construction: the file only compiles where the icon
// can be shown.
func Available() bool { return true }
